### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by alex-galych**
- Developer(s): @alex-galych 

#### Please confirm

- [ ] No new OS components - or they have been approved by legal department

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   FactFinderSdk            | patch                 |                       |

#### Release Notes

{skip}

-----------------------------------------

##### Change log

Bugfixes

- Allowing new `spryker/stock` module major dependency `^8.0.0`.

### CODE REVIEW

**Comment by dereuromark** [comment]
> Increased spryker/stock version dependency to "^8.0.0".

Thats a lie.
According to our guidelines you are

> allowing new `^8.0.0`

**Comment by dereuromark** [comment]
"repositories": [
    {
      "type": "git",
      "url": "git@github.com:FACT-Finder/FACT-Finder-PHP-Library.git"
    }
  ],

Is that still needed? They don't have it in packagist yet?

**Comment by alex-galych** [comment]
> "repositories": [
> {
> "type": "git",
> "url": "[git@github.com](mailto:git@github.com):FACT-Finder/FACT-Finder-PHP-Library.git"
> }
> ],
> 
> Is that still needed? They don't have it in packagist yet?

it is.

**Comment by alex-galych** [comment]
> > Increased spryker/stock version dependency to "^8.0.0".
> 
> Thats a lie.
> According to our guidelines you are
> 
> > allowing new `^8.0.0`

Fixed.

**Comment by dereuromark** [comment]
I fixed the quotes to code fencing for technical terms.

**Review by pyvovarov-s — APPROVED** [review]

**Pull request merged**
